"""Utility script to produce the TEC Unified Symbol Table Excel workbook."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

# Base directory assumed to be repository root when executed from any location inside the repo
REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "docs" / "TEC_Unified_Symbol_Table_v1.xlsx"

SYMBOL_ROWS = [
    {
        "Symbol_ID": "GLYPH_RING",
        "Symbol": "Glyph Ring",
        "Codepoint": "Custom/PUA",
        "TEC_Role": "Glyph",
        "Domain": "TEC-Lore",
        "Archetype": "—",
        "Gloss": "Unity, Continuity",
        "Field_Role": "Cosmic law mandala",
        "OperatorType": "n/a",
        "Composition": "Standalone frame; can wrap equations or sigils",
        "Earth_History_Link": "",
        "Status": "Draft",
        "Notes": "From Resonance_Token_Mapping.xlsx",
    },
    {
        "Symbol_ID": "FRACTAL_SPIRE",
        "Symbol": "Fractal Spire",
        "Codepoint": "Custom/PUA",
        "TEC_Role": "Glyph",
        "Domain": "TEC-Lore",
        "Archetype": "—",
        "Gloss": "Expansion, Entropy",
        "Field_Role": "Unstable energy flows",
        "OperatorType": "n/a",
        "Composition": "Stacks vertically; pairs with ∇, ∂ for gradients",
        "Earth_History_Link": "",
        "Status": "Draft",
        "Notes": "From Resonance_Token_Mapping.xlsx",
    },
    {
        "Symbol_ID": "SINE_ARC",
        "Symbol": "Sine Arc",
        "Codepoint": "U+223F (SINE WAVE)",
        "TEC_Role": "Glyph",
        "Domain": "TEC-Lore",
        "Archetype": "—",
        "Gloss": "Vibration, Frequency",
        "Field_Role": "Harmonic resonance carrier",
        "OperatorType": "infix",
        "Composition": "Combine with constants to denote modulated signals",
        "Earth_History_Link": "",
        "Status": "Draft",
        "Notes": "Brand Guide motif; Unicode in Workbench",
    },
    {
        "Symbol_ID": "COCOON_ORCHID",
        "Symbol": "Cocoon-Orchid",
        "Codepoint": "Custom/PUA",
        "TEC_Role": "Glyph",
        "Domain": "TEC-Lore",
        "Archetype": "—",
        "Gloss": "Transformation, Hunger",
        "Field_Role": "Phase transition marker",
        "OperatorType": "n/a",
        "Composition": "Encapsulates terms to denote metamorphosis",
        "Earth_History_Link": "",
        "Status": "Draft",
        "Notes": "From Resonance_Token_Mapping.xlsx",
    },
    {
        "Symbol_ID": "HALO_CORONA",
        "Symbol": "Halo/Corona",
        "Codepoint": "U+25EF (LARGE CIRCLE)",
        "TEC_Role": "Glyph",
        "Domain": "TEC-Lore",
        "Archetype": "—",
        "Gloss": "Revelation, Insight",
        "Field_Role": "Revelatory highlight",
        "OperatorType": "circumfix",
        "Composition": "Encircles focal symbol to denote insight",
        "Earth_History_Link": "",
        "Status": "Draft",
        "Notes": "Brand Guide motif",
    },
    {
        "Symbol_ID": "CONST_c",
        "Symbol": "c",
        "Codepoint": "U+0063",
        "TEC_Role": "Constant",
        "Domain": "Physics",
        "Archetype": "—",
        "Gloss": "Speed of light in vacuum",
        "Field_Role": "Signal propagation limit",
        "OperatorType": "n/a",
        "Composition": "Scalar",
        "Earth_History_Link": "Maxwell/Relativity",
        "Status": "Review",
        "Notes": "Use italic c",
    },
    {
        "Symbol_ID": "CONST_hbar",
        "Symbol": "ℏ",
        "Codepoint": "U+210F",
        "TEC_Role": "Constant",
        "Domain": "Physics",
        "Archetype": "—",
        "Gloss": "Reduced Planck constant",
        "Field_Role": "Quantum of action scale",
        "OperatorType": "n/a",
        "Composition": "Scalar",
        "Earth_History_Link": "Quantum mechanics",
        "Status": "Review",
        "Notes": "Prefer ℏ over h",
    },
    {
        "Symbol_ID": "CONST_h",
        "Symbol": "h",
        "Codepoint": "U+0068",
        "TEC_Role": "Constant",
        "Domain": "Physics",
        "Archetype": "—",
        "Gloss": "Planck constant",
        "Field_Role": "Photon energy E=hf",
        "OperatorType": "n/a",
        "Composition": "Scalar",
        "Earth_History_Link": "Quantum theory history",
        "Status": "Draft",
        "Notes": "For earth-history notes",
    },
    {
        "Symbol_ID": "CONST_G",
        "Symbol": "G",
        "Codepoint": "U+0047",
        "TEC_Role": "Constant",
        "Domain": "Physics",
        "Archetype": "—",
        "Gloss": "Newtonian G",
        "Field_Role": "Gravitational coupling",
        "OperatorType": "n/a",
        "Composition": "Scalar",
        "Earth_History_Link": "Gravitation",
        "Status": "Draft",
        "Notes": "Pair with ∇ for potential",
    },
    {
        "Symbol_ID": "CONST_Lambda",
        "Symbol": "Λ",
        "Codepoint": "U+039B",
        "TEC_Role": "Constant",
        "Domain": "Physics",
        "Archetype": "—",
        "Gloss": "Cosmological constant",
        "Field_Role": "Vacuum energy / expansion",
        "OperatorType": "n/a",
        "Composition": "Scalar",
        "Earth_History_Link": "Cosmology",
        "Status": "Draft",
        "Notes": "Uppercase Lambda",
    },
    {
        "Symbol_ID": "CONST_kB",
        "Symbol": "k_B",
        "Codepoint": "literal",
        "TEC_Role": "Constant",
        "Domain": "Physics",
        "Archetype": "—",
        "Gloss": "Boltzmann constant",
        "Field_Role": "Entropy/temperature bridge",
        "OperatorType": "n/a",
        "Composition": "Scalar",
        "Earth_History_Link": "Stat mech & info theory",
        "Status": "Draft",
        "Notes": "Use subscript formatting",
    },
    {
        "Symbol_ID": "OP_partial",
        "Symbol": "∂",
        "Codepoint": "U+2202",
        "TEC_Role": "Operator",
        "Domain": "Math",
        "Archetype": "—",
        "Gloss": "Partial derivative",
        "Field_Role": "Local change along coordinate",
        "OperatorType": "prefix",
        "Composition": "∂/∂x, ∂/∂t",
        "Earth_History_Link": "",
        "Status": "Final",
        "Notes": "Standard",
    },
    {
        "Symbol_ID": "OP_nabla",
        "Symbol": "∇",
        "Codepoint": "U+2207",
        "TEC_Role": "Operator",
        "Domain": "Math",
        "Archetype": "—",
        "Gloss": "Nabla / gradient",
        "Field_Role": "Vector differential operator",
        "OperatorType": "prefix",
        "Composition": "∇·, ∇×, ∇^2",
        "Earth_History_Link": "",
        "Status": "Final",
        "Notes": "Standard",
    },
    {
        "Symbol_ID": "OP_sigma",
        "Symbol": "Σ",
        "Codepoint": "U+2211",
        "TEC_Role": "Operator",
        "Domain": "Math",
        "Archetype": "Summation",
        "Gloss": "Aggregate/accumulation",
        "Field_Role": "Aggregate/n-ary",
        "OperatorType": "n-ary",
        "Composition": "Σ_i x_i",
        "Earth_History_Link": "",
        "Status": "Final",
        "Notes": "Standard",
    },
    {
        "Symbol_ID": "OP_pi",
        "Symbol": "∏",
        "Codepoint": "U+220F",
        "TEC_Role": "Operator",
        "Domain": "Math",
        "Archetype": "Product",
        "Gloss": "Cascaded composition",
        "Field_Role": "Product",
        "OperatorType": "n-ary",
        "Composition": "∏_i x_i",
        "Earth_History_Link": "",
        "Status": "Final",
        "Notes": "Standard",
    },
    {
        "Symbol_ID": "OP_ring",
        "Symbol": "∘",
        "Codepoint": "U+2218",
        "TEC_Role": "Operator",
        "Domain": "Math",
        "Archetype": "—",
        "Gloss": "Composition operator",
        "Field_Role": "Function composition",
        "OperatorType": "infix",
        "Composition": "f ∘ g",
        "Earth_History_Link": "",
        "Status": "Final",
        "Notes": "Standard",
    },
    {
        "Symbol_ID": "C_FIELD",
        "Symbol": "Φ_E",
        "Codepoint": "composite",
        "TEC_Role": "Field",
        "Domain": "Physics/TEC-Lore",
        "Archetype": "Unifier",
        "Gloss": "Contextual Energy field",
        "Field_Role": "Resonance substrate coupling ψ(r), φ(t)",
        "OperatorType": "n/a",
        "Composition": "Composite symbol (Phi with subscript E)",
        "Earth_History_Link": "To link earth-history symbolisms later",
        "Status": "Draft",
        "Notes": "Custom glyph next",
    },
    {
        "Symbol_ID": "TEMPORAL_FIELD",
        "Symbol": "φ(t)",
        "Codepoint": "composite",
        "TEC_Role": "Field",
        "Domain": "Physics/TEC-Lore",
        "Archetype": "—",
        "Gloss": "Temporal evolution field",
        "Field_Role": "Consciousness/time modulation",
        "OperatorType": "n/a",
        "Composition": "Scalar function of t",
        "Earth_History_Link": "",
        "Status": "Draft",
        "Notes": "Equation component",
    },
    {
        "Symbol_ID": "SPATIAL_FIELD",
        "Symbol": "ψ(r)",
        "Codepoint": "composite",
        "TEC_Role": "Field",
        "Domain": "Physics/TEC-Lore",
        "Archetype": "—",
        "Gloss": "Spatial wavefunction",
        "Field_Role": "Matter/spatial distribution",
        "OperatorType": "n/a",
        "Composition": "Scalar/vector over r",
        "Earth_History_Link": "",
        "Status": "Draft",
        "Notes": "Equation component",
    },
    {
        "Symbol_ID": "SIGIL_ELIDORAS_PRIMARY",
        "Symbol": "⟐",
        "Codepoint": "U+27D0",
        "TEC_Role": "Sigil",
        "Domain": "TEC-Lore",
        "Archetype": "—",
        "Gloss": "Elidoras primary sigil (placeholder)",
        "Field_Role": "World-identity anchor",
        "OperatorType": "n/a",
        "Composition": "Standalone",
        "Earth_History_Link": "To be defined with earth-history layers",
        "Status": "Draft",
        "Notes": "Temporary glyph",
    },
    {
        "Symbol_ID": "SIGIL_DEADLOCK",
        "Symbol": "⧖",
        "Codepoint": "U+29D6",
        "TEC_Role": "Sigil",
        "Domain": "TEC-Lore/Cosmology",
        "Archetype": "—",
        "Gloss": "Cosmic deadlock / tidal lock",
        "Field_Role": "Gravitational stasis / fatal orbit",
        "OperatorType": "n/a",
        "Composition": "Standalone or with G, Λ",
        "Earth_History_Link": "To be elaborated",
        "Status": "Draft",
        "Notes": "Metaphor; may change",
    },
]

PROVENANCE_ROWS = [
    {
        "Source": "Resonance_Token_Mapping.xlsx",
        "What": "Core resonance glyphs & meanings",
        "Provenance": "User-provided file",
    },
    {
        "Source": "✨ Tec Brand Guide — Lumina & Kaznak (expanded V1).pdf",
        "What": "Motifs & semiotics; palette; usage rules",
        "Provenance": "User-provided file",
    },
    {
        "Source": "Runic Title Language Guide — Elidoras Codex.pdf",
        "What": "Runic title style guidance & font path",
        "Provenance": "User-provided file",
    },
    {
        "Source": "2025-09-25_TEC-Symbology_Language-Workbench_v1.xlsx",
        "What": "Field schema for roles/domains/archetypes",
        "Provenance": "User-provided file",
    },
]


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    symbol_df = pd.DataFrame(SYMBOL_ROWS)
    provenance_df = pd.DataFrame(PROVENANCE_ROWS)

    with pd.ExcelWriter(OUTPUT_PATH, engine="openpyxl") as writer:
        symbol_df.to_excel(writer, sheet_name="Unified_Symbol_Table_v1", index=False)
        provenance_df.to_excel(writer, sheet_name="Provenance", index=False)

    print(f"Wrote symbol table workbook to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
